# Generated by Django 3.2.7 on 2021-11-16 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_professor_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenador_curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.coordenadorprofile')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.curso')),
            ],
        ),
    ]
