# Generated by Django 3.2.7 on 2021-10-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descricao',
            field=models.TextField(default='coisa', max_length=500),
        ),
    ]
