# Generated by Django 3.2.7 on 2021-10-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_curso_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
    ]
