# Generated by Django 3.2.7 on 2021-10-31 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211031_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presenca',
            options={},
        ),
    ]
