# Generated by Django 3.2.7 on 2021-10-12 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_curso_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos_estudante')),
                ('nome', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=6)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.curso')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.disciplina')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.estudante')),
            ],
        ),
    ]
