# Generated by Django 3.2.7 on 2021-10-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_disciplinaestudante_estudante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudante',
            name='foto',
        ),
    ]
