# Generated by Django 3.2.7 on 2021-10-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_estudante_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='matricula',
            field=models.CharField(max_length=20),
        ),
    ]
