# Generated by Django 3.2.7 on 2021-11-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordenador_curso',
        ),
    ]
