# Generated by Django 3.2.7 on 2021-11-22 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('manager', '0003_delete_coordenador_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='estudante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.estudanteprofile'),
        ),
    ]
