# Generated by Django 3.2.7 on 2021-11-26 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
        ('manager', '0006_alter_disciplina_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='dia_semana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.dia_semana'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.disciplina'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='turno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.turno'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='coordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.coordenadorprofile'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.professorprofile'),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.aula'),
        ),
    ]
