# Generated by Django 3.2.7 on 2021-11-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_estudanteprofile_curso'),
        ('manager', '0007_auto_20211126_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante_disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.disciplina')),
                ('estudante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.estudanteprofile')),
            ],
        ),
    ]
